/**
 * TypeScript interfaces and types for Email Productivity Agent
 * These types match the backend Pydantic schemas for API consistency
 * 
 * @module types
 * @description Core type definitions for the Email Productivity Agent frontend
 * 
 * Validates Requirements:
 * - 1.2: Email display with sender, subject, timestamp
 * - 2.1: Prompt configuration interface
 * - 5.1: Chat message interface
 * - 6.2: Draft structure with subject, body, follow-ups
 */

// ============================================================================
// Core Data Models
// ============================================================================

/**
 * Category tags for email classification
 * Validates: Requirements 1.2, 3.2
 */
export type CategoryTag = 'Important' | 'Newsletter' | 'Spam' | 'To-Do' | 'Uncategorized';

/**
 * Action item extracted from an email
 * Validates: Requirements 4.2, 4.3
 */
export interface ActionItem {
  id: string;
  email_id: string;
  task: string;
  deadline: string | null;
  completed: boolean;
  created_at: string; // ISO 8601 datetime string
}

/**
 * Email data model
 * Validates: Requirements 1.2, 1.4
 */
export interface Email {
  id: string;
  sender: string;
  subject: string;
  body: string;
  timestamp: string; // ISO 8601 datetime string
  category: CategoryTag | null;
  processed: boolean;
  created_at: string; // ISO 8601 datetime string
  updated_at: string; // ISO 8601 datetime string
  action_items: ActionItem[];
}

/**
 * Prompt configuration for LLM behavior
 * Validates: Requirements 2.1, 2.2
 */
export interface PromptConfig {
  id: string;
  categorization_prompt: string;
  action_item_prompt: string;
  auto_reply_prompt: string;
  created_at: string; // ISO 8601 datetime string
  updated_at: string; // ISO 8601 datetime string
}

/**
 * Email draft generated by the agent
 * Validates: Requirements 6.2, 7.1
 */
export interface Draft {
  id: string;
  email_id: string;
  subject: string;
  body: string;
  suggested_follow_ups: string[] | null;
  created_at: string; // ISO 8601 datetime string
  updated_at: string; // ISO 8601 datetime string
}

/**
 * Chat message in the Email Agent interface
 * Validates: Requirements 5.1, 5.3
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string; // ISO 8601 datetime string
}

// ============================================================================
// API Request Types
// ============================================================================

/**
 * Request to process an email (categorize and extract actions)
 */
export interface ProcessEmailRequest {
  use_llm?: boolean;
}

/**
 * Request to update prompt configuration
 */
export interface UpdatePromptRequest {
  categorization_prompt: string;
  action_item_prompt: string;
  auto_reply_prompt: string;
}

/**
 * Request to create a new draft
 */
export interface CreateDraftRequest {
  email_id: string;
  subject: string;
  body: string;
  suggested_follow_ups?: string[] | null;
}

/**
 * Request to update an existing draft
 */
export interface UpdateDraftRequest {
  subject?: string;
  body?: string;
  suggested_follow_ups?: string[] | null;
}

/**
 * Request to chat with the Email Agent
 */
export interface ChatRequest {
  message: string;
  email_id?: string | null;
  context?: Record<string, unknown> | null;
}

/**
 * Request to generate a draft reply
 */
export interface GenerateDraftRequest {
  email_id: string;
  instructions?: string | null;
}

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Response from loading the mock inbox
 */
export interface LoadInboxResponse {
  count: number;
  emails: Email[];
}

/**
 * Response from getting all emails
 */
export interface EmailListResponse {
  emails: Email[];
  count: number;
}

/**
 * Response from processing an email
 */
export interface ProcessEmailResponse {
  email_id: string;
  category: string;
  action_items: ActionItem[];
  processed: boolean;
}

/**
 * Response from deleting a draft
 */
export interface DeleteDraftResponse {
  success: boolean;
  message: string;
}

/**
 * Response from agent chat
 */
export interface ChatResponse {
  response: string;
  metadata?: Record<string, unknown> | null;
}

/**
 * Response from generating a draft
 */
export interface GenerateDraftResponse {
  draft: Draft;
}

/**
 * Response with default prompt templates
 */
export interface DefaultPromptsResponse {
  categorization_prompt: string;
  action_item_prompt: string;
  auto_reply_prompt: string;
}

// ============================================================================
// UI State Types
// ============================================================================

/**
 * Loading state for async operations
 */
export interface LoadingState {
  isLoading: boolean;
  error: string | null;
}

/**
 * API error response
 */
export interface APIError {
  detail: string;
  status?: number;
}

/**
 * Generic API response wrapper
 */
export interface APIResponse<T> {
  data?: T;
  error?: APIError;
}

// ============================================================================
// Component Props Types
// ============================================================================

/**
 * Props for InboxView component
 */
export interface InboxViewProps {
  emails: Email[];
  onEmailSelect: (emailId: string) => void;
  selectedEmailId?: string;
  isLoading: boolean;
}

/**
 * Props for PromptBrain component
 */
export interface PromptBrainProps {
  prompts: PromptConfig;
  onSave: (prompts: UpdatePromptRequest) => Promise<void>;
  isLoading: boolean;
}

/**
 * Props for EmailAgent component
 */
export interface EmailAgentProps {
  selectedEmail?: Email;
  onSendMessage: (message: string) => Promise<string>;
  chatHistory: ChatMessage[];
}

/**
 * Props for DraftEditor component
 */
export interface DraftEditorProps {
  draft: Draft;
  onSave: (draft: UpdateDraftRequest) => Promise<void>;
  onDiscard: () => void;
}
